### ISSUE TITLE
Trouble with AO3

### ISSUE THREAD

**Issue by smoov22** [ingolemo/drider#1]
For some reason, when I attempt to open an AO3 EPUB with Drider, it only is able to display the first page. When I try to advance chapters, the software blocks me off. 

Can you try to clear this up?

AO3 is Archive Of Our Own, by the way.

**Comment by ingolemo** [comment]
I checked out a few of the epubs on that site and found a bug where drider would crash when it tried to read a large numeric html entity. Many of the epubs on that site use them. I don't know if this is the cause of your issue because you didn't really give any details. I fixed the bug and pushed a new version (v0.4). Try the new version and if you're still having problems then please post a link to the epub that you're trying to read and any text that drider shows when it "blocks you off".

**Comment by smoov22** [comment]
Better! Thanks!
