### ISSUE TITLE
[Feature Request] JPEG support

### ISSUE THREAD

**Issue by CCF100** [ingolemo/drider#2]
Would it be possible to implement JPEG support for comics?

**Comment by ingolemo** [comment]
In order to make comics readable, drider would need more than just jpg support. Viewing images comfortably on the 3ds' small screen would require the ability to resize, zoom, and pan, which would mean a complete rewrite of the rendering code. It looks like it's not impossible, but I'm severely limited in what I can do due to drider being written in lpp-3ds.

I'll look into it when I find some free time, but don't hold your breath. 🤞

**Comment by ingolemo** [comment]
I just released a new version that has some limited image support. Try it out and let me know.
